name = "english-dictionary"
compatibility_date = "2024-03-20"

[site]
bucket = "./dist"

[build]
command = "bun run build"
upload.format = "directory"

[env.production]
name = "english-dictionary"
workers_dev = true

[env.production.vars]
ENVIRONMENT = "production" 